### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by HaleYan** [THUDM/GraphMAE#10]
``` 
File "/data2/haleyan/code/GraphMAE-main/graphmae/models/gin.py", line 186, in __init__
    self.norms.append(create_norm(norm)(hidden_dim))
TypeError: 'NoneType' object is not callable

```
Why do I get such an error when running the graph classification dataset?

**Comment by THINK2TRY** [comment]
@HaleYan For graph classification, `batchnorm` or `layernorm` is used as default as this often helps achieve better performance. Sorry to miss to take the no-normalization into consideration. And we have fixed this bug now. Thanks for pointing out that.
