### ISSUE TITLE
Have you tested GraphMAE on link prediction tasks?

### ISSUE THREAD

**Issue by ShadowTinker** [THUDM/GraphMAE#12]
Hi! According to the paper, you argue that the structure information may be over-emphasized. So you choose to reconstruct node attributes rather than links. But I'm quite interested in how GraphMAE performs on link prediction tasks. Intuitively, I think the node attribute masking method may perform worse than link masking method. So I would like to ask whether you have done any experiments on link prediction tasks?

**Comment by THINK2TRY** [comment]
Hi @ShadowTinker  thanks for your attention! We haven't tested our model on link prediction tasks as most graph SSL baselines are for classification tasks. But in the node attribute mask prediction, the model is also forced to reconstruct its neighbor' feature, which is more challenging than pair-wise link prediction, especially with a high mask ratio. So the model may also learn information about the existence of links.  The new task can be tried quickly based on our implementation if you are interested : ) .

**Comment by ShadowTinker** [comment]
Thanks for your kind reply and explanation!
I will try it with GraphMAE myself later.
