### ISSUE TITLE
Are the features of graph nodes in the data set all discrete features？

### ISSUE THREAD

**Issue by WangYong-Design** [THUDM/GraphMAE#13]

**Comment by THINK2TRY** [comment]
GraphMAE can be applied no matter whether the input node features lie in continuous space or discrete space. The node features of datasets like Ogbn-arxiv and Reddit are continuous vectors, and the features of Cora/Citeseer are discrete.  GraphMAE just uses the features in datasets without any designed modification.

**Comment by WangYong-Design** [comment]
thanks!
