### ISSUE TITLE
The setting of loss_fn

### ISSUE THREAD

**Issue by stuzhangqiqi** [THUDM/GraphMAE#15]
Thanks for a outstanding work, loss_fn is a very useful setup in node classification. However, the default value of loss_fn (default="byol") in the setting seems to have no corresponding operation, but only "mse" and "cse" operations. Can you share the loss operation of "byol"? Thanks again for sharing.

**Comment by THINK2TRY** [comment]
@stuzhangqiqi Thanks for your attention to GraphMAE. `byol` is the loss function used in [BYOL](https://arxiv.org/abs/2006.07733). It resembles the cosine error and equals normalized MSE. It motivates our work. 

We will correct this soon.

**Comment by YuetianW** [comment]
I'm having the same problem, which seems to block the `configs.yml`
