### ISSUE TITLE
请问能否提供一下损失函数为mse时的参数设置？

### ISSUE THREAD

**Issue by yifanQi98** [THUDM/GraphMAE#17]
你好，当损失函数设置为mse时，在cora和citeseer上的结果与论文中有较大的差异。请问能否提供一下损失函数为mse时的参数设置？谢谢！

**Comment by THINK2TRY** [comment]
hello @yifanQi98 ，感谢关注。我们没有保存使用MSE时的所有超参数。如果是实验发现用MSE结果较差的话，可以考虑缩短训练的迭代步数，performance 可能会有一定的增长。我们在使用MSE时有发现训练时间过长会导致performance下降。

**Comment by yifanQi98** [comment]
> hello @yifanQi98 ，感谢关注。我们没有保存使用MSE时的所有超参数。如果是实验发现用MSE结果较差的话，可以考虑缩短训练的迭代步数，performance 可能会有一定的增长。我们在使用MSE时有发现训练时间过长会导致performance下降。

好的，感谢!
