### ISSUE TITLE
Encoding Mask Token

### ISSUE THREAD

**Issue by cuongth95** [THUDM/GraphMAE#21]
In your code, the `enc_mask_token` is added when a node is masked. Then, that token is implicitly removed by re-masking it with zeros at the same indices in the middle before the decoder.

1. During the training, is it remain all past values or be randomly initialised?

1. Can you explain the behaviour of this token?

Thank you.

**Comment by THINK2TRY** [comment]
Thanks for your attention to GraphMAE. 
Maybe there exists some misunderstanding. Before the encoding stage, the features of masked nodes are *replaced* by the `enc_mask_token`, which is a learnable vector. And it could be observed that the features of masked nodes are first set to zeros and then added the `enc_mask_token`. So the mask_token serves as the placeholder to indicate which nodes are masked.

**Comment by cuongth95** [comment]
Hi, thank you for your answer.
Yes. However, before the decoder, you do re-mask again at masked positions. It is equivalent to learnable vector removal. Can you explain the underlying idea?

**Comment by THINK2TRY** [comment]
The intuition of the re-masking has been explained in our paper. And it is not equivalent to removing the learnable vectors. Both masked and unmasked nodes aggregate features from their neighbors and generate latent representations. The remasking operation forces the decoder to reconstruct input features of a given node based on its neighboring representations.  And our experiments show that this can help learn better representations.

**Comment by cuongth95** [comment]
Very clear. Thank you
