### ISSUE TITLE
when I download the dataset of IMDB-BINARY,allways failed.So I download local and put it in the package,it still download...and faild

### ISSUE THREAD

**Issue by danfeng-1** [THUDM/GraphMAE#22]
I have the problem when I run the :python main_graph.py --dataset IMDB-BINARY --encoder gin --decoder gin --seed 0 --device 0

It does have the network,but download still failed, even I put the data into the .dgl package，and the error Just like this:

Downloading /home/ubuntu/.dgl/IMDB-BINARY.zip from https://www.chrsmrrs.com/graphkerneldatasets/IMDB-BINARY.zip...
download failed, retrying, 4 attempts left

thanks for your apply

**Comment by THINK2TRY** [comment]
Hi, @danfeng-1 thanks for your attention. The problem may be attributed to the network failure, or the URL cannot be accessed in your terminal. If the dataset cannot be downloaded automatically, you can download it manually and put it into `.dgl/IMDB-BINARY`. And the files in the directory should be organized as follows:
```
├── IMDB-BINARY
   ├── IMDB-BINARY
   │   ├── IMDB-BINARY_A.txt
   │   ├── IMDB-BINARY_graph_indicator.txt
   │   └── IMDB-BINARY_graph_labels.txt
   ├── tu_IMDB-BINARY.bin
   └── tu_IMDB-BINARY.pkl
```
Hope it helps.

**Comment by danfeng-1** [comment]
这是来自兰丹凤邮箱的自动回复邮件。你好，你的邮件已经收到

**Comment by danfeng-1** [comment]
@THINK2TRY thanks for your apply, I put the data as the path your give，it dose work! Thanks again

**Comment by danfeng-1** [comment]
这是来自兰丹凤邮箱的自动回复邮件。你好，你的邮件已经收到
