### ISSUE TITLE
RuntimeError: Class values must be smaller than num_classes.

### ISSUE THREAD

**Issue by Mah-Zam** [THUDM/GraphMAE#23]
Hi dear author,

May I get your help for fixing the issue for running Chem? Chem is  using torch_geometric instead of DGI. I am getting the below error for all datasets.

/chem/util.py", line 248, in __call__
    atom_type = F.one_hot(data.mask_node_label[:, 0], num_classes=self.num_atom_type).float()
RuntimeError: Class values must be smaller than num_classes.

Thanks

**Comment by Mah-Zam** [comment]
self._transform = MaskAtom(num_atom_type = 119, num_edge_type = 5, mask_rate = mask_rate, mask_edge=mask_edge)
I checked and noticed you have hardcoded the num_atom_type with 119 and num_edge_type=5. What are the number for other datasets?

**Comment by Mah-Zam** [comment]
Hello Again, Yes, I used your datasets.

**Comment by THINK2TRY** [comment]
It appears that the error shown in the attached image is another case. If you have attempted to modify the code for your research, it is important to make careful changes to maintain consistency in all files.
