### ISSUE TITLE
keyword type error in GraphMAE torch_geometric

### ISSUE THREAD

**Issue by voladorlu** [THUDM/GraphMAE#28]
Hi, I just get a keyword error when running the code based on torch_geometric. The keyword "residul" seems to be type error in the gat.py, from line 56 to 70. Please double check it out.

**Comment by voladorlu** [comment]
In the evaluation.py, the "linear_probing_for_transductive_node_classiifcation" function, the parameters for the model forward step should be model(x, graph.edge_index), not model(graph, x).

**Comment by THINK2TRY** [comment]
@voladorlu Thanks for pointing out the problems. We will fix them as soon as possible.
