### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by RocZKUNP** [THUDM/GraphMAE#29]
Hello, what is the mask identification used in GraphMAE?

**Comment by THINK2TRY** [comment]
@RocZKUNP Thanks for your attention! Could you explain more about the "mask identification"? Do you mean the mask token [MASK], which is a learnable high-dimension vector ?

**Comment by RocZKUNP** [comment]
非常感谢您的回复。我的确是对于mask token [MASK] 进行提问。之前阅读过何凯明的Masked Autoencoders，它的这篇工作中是将masked像素去除，我以为在您的GraphMAE中是同样的操作。经过您的答复我明白了，所以您最后的缩放余弦误差只关注被masked的节点是因为[MASK]是可学习的高维向量，是这样吗？

**Comment by RocZKUNP** [comment]
非常感谢您的回复，我的确是对 mask token [MASK] 进行提问。经过您的答复我明白了，所以您最后的缩放余弦误差只关注被masked的节点是因为[MASK]是可学习的高维向量，是这样吗？

**Comment by THINK2TRY** [comment]
Loss 的计算关注那些在 input 中被 mask 掉的节点，相当于用剩余可见的节点特征来预测 被 mask 的节点特征。
