### ISSUE TITLE
about the CCA-SSG implementation

### ISSUE THREAD

**Issue by MR9812** [THUDM/GraphMAE#30]
您好，恭喜您发表了一篇优秀的工作，对我的启发很大～

       有一个问题想向您咨询，我在CCA-SSG的复现上遇到了一些问题，主要是在 arxiv数据集上没有搜索到合适的参数。

       在论文中没有涉及到对应baseline的超参数描述，不知能否提供你们复现所用的超参数以供参考？

非常感谢🙏

**Comment by THINK2TRY** [comment]
@MR9812 非常感谢关注！我们使用了 CCA-SSG 的[公开实现](https://github.com/hengruizhang98/CCA-SSG)，并用 GAT 作为 encoder，其他相关的参数如下：
```bash
--backbone=gat --dataname=ogbn-arxiv --der=0.5 --dfr=0 --epochs=50 --hid_dim=1024 --lambd=0.0005 --lr2=0.005 --n_layers=3 --norm=batchnorm --out_dim=2048 --wd2=0.0001
```
希望有帮助！
