### ISSUE TITLE
About random seed settings

### ISSUE THREAD

**Issue by AzureLeon1** [THUDM/GraphMAE#32]
Thank you for your wonderful work. But I have a little question about the setting of seeds in the experiments. From the provided running scripts, it seems that {0, 1, ..., 19} and {0, 1, ..., 4} are adopted in the transductive and inductive node classification experiments, respectively. Could you provide some clarity on the random seed settings used in the experiments?
Thanks

**Comment by THINK2TRY** [comment]
@AzureLeon1  hi, thanks for your attention! In our experiments, we run 20 seeds for transductive datasets and 10 seeds for inductive datasets, as the inductive datasets are relatively larger and the results are more stable than in small-scale datasets. It also takes more time to train on inductive ones so we simply put 5 random seeds in the example scripts.
