### ISSUE TITLE
I cannot run this method based on the current torch_geometric version (2.2.0)

### ISSUE THREAD

**Issue by HelloWorldLTY** [THUDM/GraphMAE#33]
Hi all, I can run successfually based on single GCN or GAT model, but if I try to call the GraphMAE model, for example, Premodel() function to generate a new model, I will meet segementation fault without any errors. Are there ant solutions towards this problem? Thanks a lot.

**Comment by HelloWorldLTY** [comment]
I install pytorch based on 
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
I install pytorch_geometric based on 
pip install torch_geometric

**Comment by THINK2TRY** [comment]
@HelloWorldLTY Hi thanks for your attention!  It seems that you are trying to run the pyg version of GraphMAE. And it is expected to follow the instruction in [pyg](https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html) for installation. In our experiments, the program runs successfully in Linux. Could you provide more details about the problem description?

**Comment by HelloWorldLTY** [comment]
Hi, I used jupyter notebook to run it and the directly error is kernel dead. 

Here are my version details:

pytorch                   1.12.1          cpu_py39h3439074_1    conda-forge
pytorch-cuda              11.7                 h778d358_3    pytorch
pytorch-lightning         2.0.0                    pypi_0    pypi
pytorch-metric-learning   2.0.1                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch

torch-geometric               2.3.0

**Comment by HelloWorldLTY** [comment]
Hi, there are two solutions I can guess for this problem. Approach 1 is using conda. Maybe you can upload your yaml file for your conda envrionment and I can set up such environment in my server. Approach 2 is using torch geometric. Sincer I only need the encoder part of your model, maybe you can consider to integrate your method into PYG. Thanks a lot!

**Comment by THINK2TRY** [comment]
Hi, below is a more detailed list of the environment information for PyTorch and PyG:
```
  - torch==1.12.0+cu113
  - torch-cluster==1.6.0
  - torch-geometric==2.2.0
  - torch-optimizer==0.3.0
  - torch-scatter==2.0.9
  - torch-sparse==0.6.15
 ```
It's possible that there may be conflicts in your current environment. To avoid this, you may consider creating a new Conda environment for your experiments. I have also uploaded the `env.yml` of my environment, which may be helpful.
