### ISSUE TITLE
你好，我运行以下命令，无法复现论文的结果，能帮我解释下为什么吗？非常感谢

### ISSUE THREAD

**Issue by zzzsh2000** [THUDM/GraphMAE#39]
你好，我运行以下命令，无法复现论文的结果，能帮我解释下为什么吗？非常感谢
ogb=1.3.6
pytorch=1.12.0
dgl-cuda11.3=0.9.1
python main_transductive.py --dataset cora --encoder gat --decoder gat --seed 0 --device 0

--- TestAcc: 0.5650, early-stopping-TestAcc: 0.5650, Best ValAcc: 0.5840 in epoch 29 ---

final_acc: 0.5650±0.0000
early-stopping_acc: 0.5650±0.0000

**Comment by THINK2TRY** [comment]
可以参考[README](https://github.com/THUDM/GraphMAE#quick-start-)中的说明，使用提供的每个数据集上更好的[超参数](https://github.com/THUDM/GraphMAE/blob/main/configs.yml)。
