### ISSUE TITLE
about the bgrl implementation

### ISSUE THREAD

**Issue by xh3204** [THUDM/GraphMAE#4]
非常感谢你们杰出的工作，对我的启发很大～

但是我在bgrl的复现上遇到了一些问题，主要是在Cora，CiteSeer， PubMed和 Ogbn-arxiv四个数据集上并没有搜索到合适的augmentation参数，即边和输入特征的drop probability。

在论文中没有涉及到对应baseline的超参数描述，不知能否提供你们复现所用的超参数以供参考？

非常感谢🙏

**Comment by cenyk1230** [comment]
Hi @xh3204,
arxiv数据集我们直接报告了原论文的结果。对于cora/citeseer/pubmed三个数据集，我们采用了GATConv。具体的一些超参（参数名称略有修改，比如layers拆解成了layer0, layer1，aug_params拆解成了p_e1, p_e2等）：
* cora: --epochs=100 --layer0=4096 --layer1=1024 --lr=0.001 --name=cora --norm=batchnorm --p_e1=0.5 --p_e2=0.3 --p_f1=0.2 --p_f2=0.5 --pred_hid=1024
* citesser: --epochs=50 --layer0=4096 --layer1=8192 --lr=0.0005 --name=citeseer --norm=batchnorm --p_e1=0.4 --p_e2=0.4 --p_f1=0.4 --p_f2=0.1 --pred_hid=4096

**Comment by xh3204** [comment]
非常感谢🙏，可能主要是中间层纬度上的差异，原来要设这么大😭
