### ISSUE TITLE
实验结果的一些问题

### ISSUE THREAD

**Issue by ZewLin** [THUDM/GraphMAE#40]
您好作者，我在cora数据集上直接运行了您给出的sh脚本，但是发现node classfication任务的准确率只有80%左右。请问是sh脚本中参数与您的实验参数不同吗？
期待您的回复，感谢！！！

**Comment by THINK2TRY** [comment]
@ZewLin 你好， 可以参考[README](https://github.com/THUDM/GraphMAE#quick-start-)中的说明，使用提供的每个数据集上更好的[超参数](https://github.com/THUDM/GraphMAE/blob/main/configs.yml)。

**Comment by ZewLin** [comment]
好的，感谢作者

**Comment by ZewLin** [comment]
Zhenyu，你好。我使用了你提供的yml中的参数，但是在cora数据集上的准去率依然只有79.9%。

发件人：Zhenyu Hou ***@***.***>
发送日期：2023-05-22 14:25:19
收件人：THUDM/GraphMAE ***@***.***>
抄送人：ZewLin ***@***.***>,Mention ***@***.***>
主题：Re: [THUDM/GraphMAE] 实验结果的一些问题 (Issue #40)

@ZewLin 你好， 可以参考README中的说明，使用提供的每个数据集上更好的超参数。
