### ISSUE TITLE
关于使用gcn作为encoder的问题

### ISSUE THREAD

**Issue by zhenshuozhang** [THUDM/GraphMAE#41]
作者您好，我试图在cora数据集上使用gcn作为encoder，但是node classification精度只有71%左右，能麻烦提供一下使用GCN的超参数吗

**Comment by zhenshuozhang** [comment]
修正一下，不是用GCN作encoder的问题，是好像只有decoder用gat才有效

**Comment by THINK2TRY** [comment]
@dusur 感谢关注GraphMAE！使用不同的 GNN 作为 decoder 的效果会存在差异，在[paper](https://arxiv.org/pdf/2205.10803.pdf) 的 Table 5 中也report了用不同GNN作为 decoder 的表现。我们也发现在节点分类上，GAT确实是一个更好的选择，这可能是因为 attention 在节点特征重建的时候比较重要。

**Comment by zhenshuozhang** [comment]
> @dusur 感谢关注GraphMAE！使用不同的 GNN 作为 decoder 的效果会存在差异，在[paper](https://arxiv.org/pdf/2205.10803.pdf) 的 Table 5 中也report了用不同GNN作为 decoder 的表现。我们也发现在节点分类上，GAT确实是一个更好的选择，这可能是因为 attention 在节点特征重建的时候比较重要。

请问table4中，使用GCN和MLP作为decoder的超参数是怎么设置的？我本地跑，如果不是gat作decoder，cora上的精度只有70左右

**Comment by THINK2TRY** [comment]
> > @dusur 感谢关注GraphMAE！使用不同的 GNN 作为 decoder 的效果会存在差异，在[paper](https://arxiv.org/pdf/2205.10803.pdf) 的 Table 5 中也report了用不同GNN作为 decoder 的表现。我们也发现在节点分类上，GAT确实是一个更好的选择，这可能是因为 attention 在节点特征重建的时候比较重要。
> 
> 请问table4中，使用GCN和MLP作为decoder的超参数是怎么设置的？我本地跑，如果不是gat作decoder，cora上的精度只有70左右

我们没有保留GCN作为decoder的超参数设置，不过GCN作为decoder和使用GAT超参数确实存在一定的差异。可以考虑使用不同的训练时间（epochs）、weight-decay等进行调节。
