### ISSUE TITLE
关于NCI1的结果

### ISSUE THREAD

**Issue by songshuhan** [THUDM/GraphMAE#42]
作者您好，我在完全使用您的代码和超参数的情况下在NCI1上的准确率只有68%左右，和论文里的80%相差巨大，其他的所有结果倒是都基本相似，想问下关于NCI1的config设置是否哪里公布的有问题呢？

**Comment by songshuhan** [comment]
我的问题，已经解决

**Comment by ZewLin** [comment]
@songshuhan 您好，能讲一下您是怎么解决的吗，我也有类似的问题

**Comment by AliothF** [comment]
> 作者您好，我在完全使用您的代码和超参数的情况下在NCI1上的准确率只有68%左右，和论文里的80%相差巨大，其他的所有结果倒是都基本相似，想问下关于NCI1的config设置是否哪里公布的有问题呢？

您好，能讲一下您是怎么解决的吗，我也有类似的问题
