### ISSUE TITLE
Code about Reddit Dataset

### ISSUE THREAD

**Issue by yolandalalala** [THUDM/GraphMAE#43]
Hi, thanks for releasing the code of your excellent work in Graph Neural Networks! 

I got a question regarding the Reddit Dataset. Your results on Reddit presented in your paper shows promising result and fabulous generalizability of GraphMAE, so that I hope to reproduce that result myself. However, if I understand correctly, data loader for Reddit is not included. I assume there is some special accommodation on Reddit is needed to train the GraphMAE because Reddit has 23k nodes and 11m edges. Could you please kindly provide your code for processing Reddit Dataset? Thank you so much for your consideration.

**Comment by THINK2TRY** [comment]
@yolandalalala Thanks for your attention to GraphMAE! In fact, we conduct full-batch training for Reddit dataset as well as Cora without any mini-batch data loader. A direct way is to use a GPU with larger memory so you can run the program and reproduce the results. If you would to use a dataloader for mini-batch training, you can write a customized one using the dataloaders provided in DGL or refer to our implementation [here](https://github.com/THUDM/GraphMAE2).
