### ISSUE TITLE
关于VGAE用于节点分类问题

### ISSUE THREAD

**Issue by songshuhan** [THUDM/GraphMAE#44]
貌似论文里只有链接预测的数据，我自己利用VGAE的链接预测预训练的模型，然后利用encoder在下游任务做节点分类预测效果相差很远，比如cora的准确率只有45%，但您的测试有71%，想问下作者的VGAE的节点分类的数据是怎么得出的

**Comment by THINK2TRY** [comment]
@songshuhan 你好，关于GAE的结果是参照之前工作([CCA-SSG](https://proceedings.neurips.cc/paper/2021/hash/00ac8ed3b4327bdd4ebbebcb2ba10a00-Abstract.html), [MVGRL](http://proceedings.mlr.press/v119/hassani20a.html)) report 的结果，我们没有去重新复现。建议也可以参照现有的实现([1](https://github.com/tkipf/gae), [2](https://github.com/zfjsail/gae-pytorch))看一下结果
