### ISSUE TITLE
Find implement issue in PyG version

### ISSUE THREAD

**Issue by fs302** [THUDM/GraphMAE#47]
Hi, I have encountered an error while running the PyG version of GraphMAE using the command ﻿`python main_transductive.py --dataset cora --encoder gat --decoder gat --seed 0 --device 0`. The error message states:
```
File "../GraphMAE/graphmae/evaluation.py", line 52, in linear_probing_for_transductive_node_classiifcation     
out = model(graph, x) 
TypeError: dropout(): argument 'input' (position 1) must be Tensor, not Data 
```
While it works fine by `sh scripts/run_transductive.sh cora 0`.
I think it is because the args setting `linear_prob` cause the model mis-assign in `linear_probing_for_transductive_node_classiifcation`.

**Comment by THINK2TRY** [comment]
@fs302 Thanks for your attention, and sorry for the late response. You are right as the evaluation procedures are different depending on whether setting`--linear_prob`. Initially, we would like to implement finetuning without freezing GNN parameters but this setting is discarded in later evaluation. And the code is retained. Now all reported results are under the `--linear_prob` setting.
