### ISSUE TITLE
link prediction

### ISSUE THREAD

**Issue by Lipxiao** [THUDM/GraphMAE#49]
你好，GraphMAE在论文中主要应用在分类任务上，为什么没有用到链路预测任务呢？通过对mask的节点特征重建，是不是也可以通过Z*Z.T的方式构建边呢

**Comment by THINK2TRY** [comment]
@Lipxiao 你好。从应用的角度看，GraphMAE也可以用在link prediction 的任务上，因为GraphMAE训练和学习 embedding 和下游任务是独立的。之前我们的论文主要关注在分类任务上，如果有兴趣也可以在 link prediction 上进行尝试和评测。不过从 link prediction 任务的经验来看，加入额外的边重建的目标可能会在链接预测任务上对效果带来进一步的提升，
