### ISSUE TITLE
Confusion about transfer learning

### ISSUE THREAD

**Issue by DuanhaoranCC** [THUDM/GraphMAE#5]
I'm working on your transfer learning part, but there are a few places to ask the authors for advice. as follows:
```python
node_attr_label = batch.node_attr_label
masked_node_indices = batch.masked_atom_indices
pred_node = dec_pred_atoms(node_rep, batch.edge_index, batch.edge_attr, masked_node_indices)
if loss_fn == "sce":
   loss = criterion(node_attr_label, pred_node[masked_node_indices])
```
Why is the restored feature an atomic type instead of a node feature? The features of all atoms are 2-dimensional, the first dimension is the atom type, and the second dimension is the chirality, so is it meaningless to restore such node features?

**Comment by THINK2TRY** [comment]
Hi @DuanhaoranCC , thanks for your attention. In our experiments, we find that reconstructing chirality doesn't contribute to better performance. Possible reasons could be that the distribution of chirality is biased or it is very easy to predict the property. In fact, the results wouldn't vary a lot if reconstructing both atomic type and chirality.

**Comment by DuanhaoranCC** [comment]
Thank you!
