### ISSUE TITLE
inductive node classification

### ISSUE THREAD

**Issue by ghjksnsi** [THUDM/GraphMAE#50]
您好，我在运行Node Classification这一部分代码时，根据您论文中的设置，用Cora、Citeseer、Pubmed数据集进行 transductive learning，用PPI和Reddit数据集进行inductive learning，所得到的结果和您论文中的结果基本一致。我现在想在Cora、Citeseer、Pubmed数据集上进行inductive learning，于是我使用命令行sh scripts/run_inductive.sh cora/citeseer/pubmed 0 运行，但是得到的Node Classification的精度比较低（只有30%-40%），请问这是哪里出了问题，是我没有对数据集进行预处理吗

**Comment by THINK2TRY** [comment]
@ghjksnsi 你好，非常感谢关注。transudctive 和 inductive 下数据加载的流程不太一致。inductive的情形下 training 阶段只会使用 training nodes 而不能访问其他节点。所以可以看一下是否是数据的影响。
