### ISSUE TITLE
how to set hyperparameters（e.g. num_hidden, num_heads）

### ISSUE THREAD

**Issue by Lipxiao** [THUDM/GraphMAE#53]
你好！请问如何设置数据集的超参数，num_hidden和num_heads等。在config.yaml提供了dataset的超参数设置，但是我发现pubmed dataset中node feature的长度是500,但是该数据集的num_hidden是1024,如何理解500--> 1024的设置呢?什么情况下需要将映射到一个更高维度的空间呢？

**Comment by Lipxiao** [comment]
如果node feature长度是512，将num_hidden设置为1024还是256（升维 or 降维）?

**Comment by THINK2TRY** [comment]
@Lipxiao 你好，num-hidden 是网络中隐层的大小，与输入 node features 大小是独立的。一般情况下 num-hidden 比 input features 要大会更好，可以在 512/1024 等范围内进行尝试。

**Comment by Lipxiao** [comment]
> cora数据集的input features是1422,num_hidden设置的是512；
pubmed 数据集的input feature是500, num_hidden设置的是1024；
citeseer数据集的input feature是3703, num_hidden设置的是512；
一般情况下num-hidden 要比 input features 小吧？（因为很多数据的input feature有上千维）。为什么对pubmed设置了一个num_hidden大于input features的数值呢？是尝试了不同的设置这个结果最好吗？

**Comment by THINK2TRY** [comment]
一般情况下会选择 512 / 1024，cora / citeseer 是由于稀疏特征所以维度很高，一般 num-hidden 的设置和 input-feature dim 没有必然的关系和要求。

**Comment by Lipxiao** [comment]
明白了，感谢您耐心的回复
