### ISSUE TITLE
Question about dataset of transfer learning

### ISSUE THREAD

**Issue by StylesZhang** [THUDM/GraphMAE#54]
The dataset Chem (Bace, Bbbp, etc.) used 1.0x version of PyG to produce, but you use  2.0.3 torch_geometric. Then the dataset downloaded from the original link can't be used directly. How did you solve this problem?
![image](https://github.com/THUDM/GraphMAE/assets/72289283/21ab98c5-61a3-4f1b-9af4-26aeb6bdba7d)

**Comment by THINK2TRY** [comment]
@HeyMercer Hi, you can remove the existing `processed/` directory and try again. The program will generate new processed files automatically.
