### ISSUE TITLE
请问一般适用多大的图？

### ISSUE THREAD

**Issue by CheungZeeCn** [THUDM/GraphMAE#6]
我有个百万级别节点的图，看了下feat那块，如果每个节点feat都是768维的话，光feat部分就40G了，请问这个时候模型还适用吗？我仅有11G的卡。

**Comment by THINK2TRY** [comment]
如果图本身大小超出硬件资源的限制的话，可以和图上的采样策略结合（比如ClusterGCN、GraphSAINT）进行训练，这样可以显著减少GPU显存的占用。

**Comment by CheungZeeCn** [comment]
感谢感谢~
