### ISSUE TITLE
Academic Consultation

### ISSUE THREAD

**Issue by XinPeng97** [THUDM/GraphMAE#7]
Dear Authors,

Congratulations on your newly published KDD 2022 paper: GraphMAE: Self-Supervised Masked Graph Autoencoders. We found its idea interesting and inspiring, and would like to do further research over it.

Recently we run this public source code on NCI1 dataset for graph classification and the reproduced result is merely 76.9%, which exists a large gap compared to the reported result (80.4%) in the main paper. Would you please share the complete parameter setting of NCI1 with us for academic research?

Best regards

**Comment by THINK2TRY** [comment]
@XinPeng97 Thanks for your attention to our work. The important hyperparameters we tuned are listed in this [file](https://github.com/THUDM/GraphMAE/blob/main/configs.yml). And all hyperparameters will be printed when running the experiment. The reported results can be reproduced by running `scripts/run_graph.sh NCI1 <gpu_id>`.  And the experiments are conducted on NVIDIA 2080Ti. Could you provide more details about your experiment?

**Comment by XinPeng97** [comment]
Thanks for your reply!
