### ISSUE TITLE
in edcoder.py line:254

### ISSUE THREAD

**Issue by ak422** [THUDM/GraphMAE#8]
if self._decoder_type == "mlp":
            recon = self.decoder(rep)
the parameter of  self.decoder in line 254 missing 1 required positional argument.

**Comment by THINK2TRY** [comment]
@ak422 Thanks for your attention to our work! The input of the decoder is the node feature matrix only when the decoder is a linear layer or MLP. If the code doesn't run successfully, maybe you could give more details?

**Comment by ak422** [comment]
sorry ,it's my fault, I just set the self._decoder_type =  "mlp" before the "if" condition, so the decoder is not correct. Thank you for your reply.
