### ISSUE TITLE
dgl._ffi.base.DGLError: [21:48:49] /opt/dgl/src/runtime/c_runtime_api.cc:88: Check failed: allow_missing: Device API gpu is not enabled. Please install the cuda version of dgl.

### ISSUE THREAD

**Issue by HaleYan** [THUDM/GraphMAE#9]
When I run the scripts, error occurs.
cuda = 11.1
python = 3.6
pytorch = 1.9

**Comment by THINK2TRY** [comment]
Hi, @HaleYan , it seems to be the problem of dgl, and you are expected to install the cuda version of dgl according to your environment by referring to this[ link](https://www.dgl.ai/pages/start.html).

**Comment by HaleYan** [comment]
Thank you!
